import Head from 'next/head';
import Layout from '@/components/Layout';

export default function Home() {
  return (
    <>
      <Head>
        <title>Weilie 拜拜 BuyBuy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1 className="text-3xl font-bold text-center">Weilie 拜拜 BuyBuy</h1>
        <div className='flex justify-center'>
        <button className="mt-20 w-32 h-32  shadow-md	bg-slate-50	 rounded-full cursor-pointer text-6xl">&#128079;</button>
        </div>
      </Layout>
      <footer></footer>
    </>
  );
}
